# Generated by Django 3.2.5 on 2021-07-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeforcesUsers',
            new_name='CodeforcesUser',
        ),
        migrations.AlterModelOptions(
            name='codeforcesuser',
            options={'ordering': ['-rating']},
        ),
    ]
