# Generated by Django 5.1.5 on 2026-03-28 20:41

import leaderboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(
                default=leaderboard.models.get_current_timestamp
            ),
        ),
        migrations.CreateModel(
            name="UnifiedScoreHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=64)),
                ("date", models.DateField(db_index=True)),
                ("total_score", models.FloatField(default=0.0)),
                ("github_score", models.FloatField(default=0.0)),
                ("cf_score", models.FloatField(default=0.0)),
                ("cc_score", models.FloatField(default=0.0)),
                ("lt_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("username", "date")},
            },
        ),
    ]
