# Generated by Django 3.2.1 on 2023-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeforcesuser',
            name='last_activity',
            field=models.PositiveIntegerField(default=253402300800.0),
        ),
    ]
