# Generated by Django 3.2.4 on 2023-10-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_codeforcesuser_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeforcesfriends',
            name='user',
        ),
        migrations.RemoveField(
            model_name='githubfriends',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leetcodefriends',
            name='user',
        ),
        migrations.RemoveField(
            model_name='openlakefriends',
            name='user',
        ),
        migrations.DeleteModel(
            name='CodechefFriends',
        ),
        migrations.DeleteModel(
            name='CodeforcesFriends',
        ),
        migrations.DeleteModel(
            name='GithubFriends',
        ),
        migrations.DeleteModel(
            name='LeetcodeFriends',
        ),
        migrations.DeleteModel(
            name='OpenlakeFriends',
        ),
    ]
