# Generated by Django 3.2.1 on 2023-06-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_codeforcesuser_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeforcesuser',
            name='last_activity',
            field=models.BigIntegerField(default=253402300800.0),
        ),
    ]
