# Generated by Django 3.2.5 on 2021-07-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20210720_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeforcesuser',
            name='username',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
