# Generated by Django 5.1.5 on 2025-02-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0003_auto_20231009_1114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1738653325.13413),
        ),
    ]
