# Generated by Django 5.1.5 on 2025-06-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0003_alter_codeforcesuser_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1749401201.274039),
        ),
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
