# Generated by Django 3.2.5 on 2021-07-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("leaderboard", "0003_alter_codeforcesuser_username")]

    operations = [
        migrations.AddField(
            model_name="codeforcesuser",
            name="avatar",
            field=models.CharField(default="", max_length=256),
        )
    ]
