# Generated by Django 3.2.4 on 2023-06-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20230602_1955'),
        ('leaderboard', '0003_alter_codeforcesuser_last_activity'),
    ]

    operations = [
    ]
