# Generated by Django 5.1.5 on 2025-02-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0004_alter_codeforcesuser_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1738750367.042801),
        ),
    ]
