# Generated by Django 3.2.5 on 2021-07-23 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("leaderboard", "0004_codeforcesuser_avatar")]

    operations = [
        migrations.CreateModel(
            name="CodeforcesUserRatingUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField(default=0)),
                ("prev_index", models.PositiveIntegerField(default=0)),
                ("rating", models.PositiveIntegerField(default=0)),
                ("timestamp", models.PositiveIntegerField(default=0)),
                (
                    "cf_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaderboard.codeforcesuser",
                    ),
                ),
            ],
            options={"ordering": ["timestamp"]},
        )
    ]
