# Generated by Django 5.1.5 on 2025-06-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0004_alter_codeforcesuser_last_activity_alter_user_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1750866894.015364),
        ),
    ]
