# Generated by Django 5.1.5 on 2026-02-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0005_alter_codeforcesuser_last_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtcoderUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64, unique=True)),
                ("rating", models.PositiveIntegerField(default=0)),
                ("highest_rating", models.PositiveIntegerField(default=0)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-rating"],
            },
        ),
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1770403208.647598),
        ),
    ]
