# Generated by Django 3.2.5 on 2021-07-25 08:52

from django.db import migrations, models
import django.db.models.deletion
import leaderboard.models


class Migration(migrations.Migration):

    dependencies = [("leaderboard", "0005_codeforcesuserratingupdate")]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuserratingupdate",
            name="cf_user",
            field=models.ForeignKey(
                default=leaderboard.models.get_default_cf_user,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating_updates",
                to="leaderboard.codeforcesuser",
            ),
        )
    ]
