# Generated by Django 5.1.5 on 2026-03-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0006_alter_codeforcesuser_last_activity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1774466023.592439),
        ),
    ]
