# Generated by Django 5.1.5 on 2025-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0008_alter_codeforcesuser_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="codeforcesuser",
            name="total_solved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="codeforcesuser",
            name="total_submissions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1740068051.403886),
        ),
    ]
