# Generated by Django 5.1.5 on 2026-03-10 11:00

import leaderboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0011_alter_codeforcesuser_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(
                default=leaderboard.models.get_default_cf_last_activity
            ),
        ),
    ]
