# Generated by Django 5.1.5 on 2025-02-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0011_alter_codeforcesuser_last_activity_usertasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertasks",
            old_name="user",
            new_name="username",
        ),
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1740474125.655775),
        ),
    ]
