# Generated by Django 5.1.5 on 2025-02-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0012_rename_user_usertasks_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1740474911.289621),
        ),
    ]
