# Generated by Django 3.2.4 on 2022-09-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0013_rename_commits_githubuser_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='repositories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
