# Generated by Django 5.1.5 on 2025-02-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0013_alter_codeforcesuser_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1740474969.307117),
        ),
    ]
