# Generated by Django 5.1.5 on 2025-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0014_alter_codeforcesuser_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1740475250.16963),
        ),
    ]
