# Generated by Django 5.1.5 on 2026-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0014_postvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernames",
            name="ac_uname",
            field=models.CharField(default="", max_length=64),
        ),
    ]
