# Generated by Django 3.2.4 on 2022-10-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0015_openlakecontributer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenLakeContributer',
            new_name='openlakeContributor',
        ),
    ]
