# Generated by Django 5.1.5 on 2025-02-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0015_alter_codeforcesuser_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertasks",
            name="starred",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1740475337.589469),
        ),
    ]
