# Generated by Django 5.1.5 on 2026-03-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0015_usernames_ac_uname"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernames",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
    ]
