# Generated by Django 3.2.4 on 2022-12-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0016_rename_openlakecontributer_openlakecontributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('cc_uname', models.CharField(max_length=64)),
                ('cf_uname', models.CharField(max_length=64)),
                ('gh_uname', models.CharField(max_length=64)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
