# Generated by Django 5.1.5 on 2026-03-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0016_usernames_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernames",
            name="location",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="usernames",
            name="occupation",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="usernames",
            name="organization",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
