# Generated by Django 5.1.5 on 2025-02-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0016_usertasks_starred_alter_codeforcesuser_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertasks",
            name="solved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1740475394.209269),
        ),
    ]
