# Generated by Django 5.1.5 on 2026-03-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0017_usernames_location_usernames_occupation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leetcodeuser",
            name="calendar_data",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
