# Generated by Django 5.1.5 on 2025-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0018_alter_codeforcesuser_last_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertasks",
            name="total_solved_now",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1740577896.599077),
        ),
    ]
