# Generated by Django 5.1.5 on 2026-03-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0002_alter_codeforcesuser_last_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codechefuser",
            name="calendar_data",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
