# Generated by Django 3.2.4 on 2023-01-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0019_usernames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernames',
            name='cc_uname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='usernames',
            name='cf_uname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='usernames',
            name='gh_uname',
            field=models.CharField(max_length=64),
        ),
    ]
