# Generated by Django 5.1.5 on 2025-03-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0019_usertasks_total_solved_now_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(default=1741234126.178099),
        ),
        migrations.AlterField(
            model_name="usertasks",
            name="title",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
