# Generated by Django 5.1.5 on 2026-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0021_leetcodeuser_calendar_data_usernames_ac_uname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="join_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
