# Generated by Django 3.2.4 on 2023-01-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0021_auto_20230106_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetcodeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('ranking', models.PositiveIntegerField(default=0)),
                ('easy_solved', models.PositiveIntegerField(default=0)),
                ('medium_solved', models.PositiveIntegerField(default=0)),
                ('hard_solved', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ranking'],
            },
        ),
    ]
