# Generated by Django 5.1.5 on 2026-03-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0002_alter_codeforcesuser_last_activity_and_more"),
        ("leaderboard", "0022_alter_organization_join_code"),
    ]

    operations = []
