# Generated by Django 3.2.4 on 2023-01-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0023_remove_usernames_ol_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcodeuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
