# Generated by Django 5.1.5 on 2026-03-29 11:10

import leaderboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0023_merge_20260329_1109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforcesuser",
            name="last_activity",
            field=models.BigIntegerField(
                default=leaderboard.models.get_current_timestamp
            ),
        ),
    ]
