# Generated by Django 3.2.4 on 2023-01-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0024_leetcodeuser_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='codechefuser',
            name='avatar',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='avatar',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='leetcodeuser',
            name='avatar',
            field=models.CharField(default='', max_length=256),
        ),
    ]
