# Generated by Django 5.1.5 on 2026-03-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0024_alter_codeforcesuser_last_activity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="unifiedscorehistory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="unifiedscorehistory",
            name="user_id",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name="unifiedscorehistory",
            unique_together={("user_id", "date")},
        ),
    ]
